repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      stages: [commit]
      args: [--config=.flake8]
      language: system
      files: \.py$
    - id: isort
      name: isort
      entry: isort
      stages: [commit]
      language: system
      files: \.py$
