CLOSE_TAB_MOUSE = '<ButtonRelease-2>'

COLUMN_EDIT_UP = '<Alt-Shift-Up>'
COLUMN_EDIT_DOWN = '<Alt-Shift-Down>'
COLUMN_EDIT_LEFT = '<Alt-Shift-Left>'
COLUMN_EDIT_RIGHT = '<Alt-Shift-Right>'
COLUMN_EDIT_HOME = '<Alt-Shift-Home>'
COLUMN_EDIT_END = '<Alt-Shift-End>'
COLUMN_EDIT_NEXT = '<Alt-Shift-Next>'
COLUMN_EDIT_PRIOR = '<Alt-Shift-Prior>'
COLUMN_EDIT_DOC_HOME = '<Control-Alt-Shift-Home>'
COLUMN_EDIT_DOC_END = '<Control-Alt-Shift-End>'
COLUMN_EDIT_DRAG = '<Alt-Shift-B3-Motion>'
