name: Build Pyrite
on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    needs: setup
    name: Run tests

    steps:
      - name: Run tests with pytest
        run: pytest
        env:
          PYTHONPATH: .

  lint:
    needs: setup
    name: Lint code

    steps:
      - name: Lint code base with flake8
        run: flake8
